---
# tasks file for wordpress

# WordPress Configuration

- block:
  - name: Download and unpack latest WordPress
    unarchive:
      src: https://wordpress.org/latest.tar.gz
      dest: "/var/www/{{ productstar_wordpress_http_host }}"
      remote_src: yes
      creates: "/var/www/{{ productstar_wordpress_http_host }}/wordpress"
    tags: [ wordpress ]

  - name: Set ownership
    file:
      path: "/var/www/{{ productstar_wordpress_http_host }}"
      state: directory
      recurse: yes
      owner: www-data
      group: www-data
    tags: [ wordpress ]

  - name: Set permissions for directories
    shell: "/usr/bin/find /var/www/{{ productstar_wordpress_http_host }}/wordpress/ -type d -exec chmod 750 {} \\;"
    tags: [ wordpress ]

  - name: Set permissions for files
    shell: "/usr/bin/find /var/www/{{ productstar_wordpress_http_host }}/wordpress/ -type f -exec chmod 640 {} \\;"
    tags: [ wordpress ]

  - name: Set up wp-config
    template:
      src: "templates/wp-config.php.j2"
      dest: "/var/www/{{ productstar_wordpress_http_host }}/wordpress/wp-config.php"
    tags: [ wordpress ]
  
  become: true